language: java

env:
  global:
    - SONATYPE_USERNAME=ph@phloc.com
    - secure: "BuHUzy4PgH3wwxXpH2L4VipF6l70oAMiZKp2/LKho/ke9MxR4LDHU819guikX0mLGta0lohT48OEsycKevbxFethP1ouJo6/WpX5plpRYbaCngnm4a9VqRHMBnNTvmpyANUPoQeJKhRclHcvmmVvT
uk/A/pAkz7LBU1CHHpeHPXXlUbGNS8wm2WmkfTKYDeT/hG0Iwz+qN/wVoVNBP+euNCpZH7IW6IVzRwEpfZtPQV/CKsq2XC5h48xkRh4DSj/TyieUJHhhVLqygjDpz9kfaRpT5kvAABrS2YsXXlSN/foZkfWmukL+
PPSw6XDkTSAMbDScUE/MacrJ/Xl8Ji8IpO0SmBSQ4yu17GawjwkvSCWqdt/ZRltgU8/f7ZIt/9RoVPYq+zYkffhpZeq+ZAJ0iA/8Q7eGK+HkGlLiLul2xxLEvlcINJhy+LqEdGxNZm7El+5tqX6wwYAA3EPrJ3uf
LRZ3xRcplNgqha/VNnt/7oquxc5nQ/UE1ZQ82AVWuRxkbv4FU+0VuUewrLTAZqOdzmIsx+WU1wceQVPKxY8fzN5WnOeZ9ymcf4U9zH9f54gNMn2huADElOxJB4dIWipNNq3hc2iPYPYPL9NhXLO6MSy92IA9vVle
sIisSgJhEo4W4u80CJ2jwzSVTnG28DnJ28Ct+odT0B6Z0kZft/zfb8="    

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U
  
cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      jdk: oraclejdk8
      after_success:
        - mvn deploy --settings travis-settings.xml -DskipTests=true -B -P travis-deploy
    - stage: test
      jdk: oraclejdk11
    - stage: test
      jdk: openjdk11
